FIxup - _enable introduced
Traceback (most recent call last):
  File "bash\balt.py", line 2030, in DoItemMenu
    self.itemMenu.PopupMenu(self,Link.Frame,selected)
  File "bash\balt.py", line 2085, in PopupMenu
    link.AppendToMenu(menu,parent,*args)
  File "bash\basher.py", line 10520, in AppendToMenu
    link.AppendToMenu(subMenu,window,data)
  File "bash\basher.py", line 10416, in AppendToMenu
    InstallerLink.AppendToMenu(self,menu,window,data)
  File "bash\basher.py", line 7745, in AppendToMenu
    menuItem = wx.MenuItem(menu, self.id, self.text, self.help, self.kind)
AttributeError: InstallerConverter_Create instance has no attribute 'text'